# Generated by Django 4.2.7 on 2024-10-06 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lecture_specialist_specialistlecture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 6, 20, 47, 42, 721939, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
