# Generated by Django 4.2.7 on 2024-09-22 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_lecture_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='field',
        ),
        migrations.RemoveField(
            model_name='specialist',
            name='price',
        ),
        migrations.AddField(
            model_name='lecture',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата занятия'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='room',
            field=models.CharField(blank=True, null=True, verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 21, 37, 14, 770429, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
