# Generated by Django 4.2.7 on 2024-09-22 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_lecture_field_remove_specialist_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 21, 40, 41, 986182, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='specialistlecture',
            name='value',
            field=models.CharField(blank=True, null=True, verbose_name='Поле м-м'),
        ),
    ]
